PROJECT_NAME: mirror-medpoint
PROJECT_ID: nsysxbfavdctxapbbwwy
DEPLOYMENT_TARGET: cloud

ACCESS_TOKEN: sbp_7db25576446d39d2182bc17b8c70573270f1cbfa
ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zeXN4YmZhdmRjdHhhcGJid3d5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQyNjg3MjYsImV4cCI6MjA0OTg0NDcyNn0.0bF3Alo7Jj6FPXizVMTHyN_bd-FT2LYAc1DyhQXhDhY
SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zeXN4YmZhdmRjdHhhcGJid3d5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczNDI2ODcyNiwiZXhwIjoyMDQ5ODQ0NzI2fQ.SvJ1lVBpIGDobagM3ct45fPbB22z4vFWGSINanawcUk

SUPABASE_API_URL: https://api.supabase.com
SUPABASE_API_BASE_PATH: 
SUPABASE_PUBLIC_URL: https://nsysxbfavdctxapbbwwy.supabase.co

SERVER_HOST: 127.0.01
SERVER_PORT: 8002

ENVIRONMENT: development
VERSION: 1.0.0

BREAKER_ENABLE: true

TRACE_ENABLE: false
TRACE_COLLECTOR: 
TRACE_COLLECTOR_ENDPOINT: 

CORS_ALLOWED_ORIGINS:
CORS_ALLOWED_METHODS:
CORS_ALLOWED_HEADERS:
